#!/bin/bash
# California License Data Download Helper Script
# CA has two options: Paid database ($235) OR Free PDF extraction

echo "California License Data Download Helper"
echo "========================================"
echo ""
echo "California has TWO download options:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 1: Paid Database (RECOMMENDED) - $235"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  URL: https://www.cslb.ca.gov/onlineservices/dataportal/"
echo "  Cost: $235 (one-time purchase)"
echo "  Format: Text file (easier to parse than PDF)"
echo "  File: LICENSE MASTER"
echo ""
echo "  What you get:"
echo "  - ~50,000 active contractor licenses"
echo "  - Business name, address, phone, classifications"
echo "  - Bond info, workers comp, license status"
echo "  - Renewed or expired-but-renewable licenses"
echo ""
echo "  Target classifications:"
echo "  - C-10: Electrical Contractor"
echo "  - C-7: Low Voltage Contractor"
echo "  - C-20: HVAC Contractor"
echo ""
echo "  Steps:"
echo "  1. Visit https://www.cslb.ca.gov/onlineservices/dataportal/"
echo "  2. Look for 'Purchase Database Files'"
echo "  3. Order LICENSE MASTER file ($235)"
echo "  4. Receive download link via email"
echo "  5. Save to: output/state_licenses/ca_licenses_raw_20251031.txt"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 2: Free PDF (Budget option)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  URL: https://www.cslb.ca.gov/onlineservices/dataportal/ContractorList"
echo "  Cost: FREE"
echo "  Format: PDF (requires extraction)"
echo ""
echo "  Steps:"
echo "  1. Visit https://www.cslb.ca.gov/onlineservices/dataportal/ContractorList"
echo "  2. Download PDFs for each classification:"
echo "     - C-10 (Electrical)"
echo "     - C-7 (Low Voltage)"
echo "     - C-20 (HVAC)"
echo "  3. Extract data using PDF parser"
echo "  4. Save to: output/state_licenses/ca_c10.pdf, ca_c7.pdf, ca_c20.pdf"
echo ""
echo "  Note: Requires PDF parsing (more complex)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "RECOMMENDATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Use OPTION 1 (Paid Database) if budget allows."
echo "  - Easier to parse (text file vs PDF)"
echo "  - More comprehensive data"
echo "  - Official CSLB source"
echo "  - One-time cost: $235"
echo ""
echo "  Expected Results:"
echo "  - ~50,000 CA contractor licenses"
echo "  - ~520 CA-based OEM contractors in database"
echo "  - Expected ~150-200 matches (30-40% match rate)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Once you have the CA license data file, run:"
echo ""
echo "  python3 scripts/run_tier1_cross_reference.py \\"
echo "      --license-files output/state_licenses/ca_licenses_raw_20251031.txt \\"
echo "      --oem-contractors output/grandmaster_list_expanded_20251029.csv \\"
echo "      --output output/ca_cross_referenced_20251031.csv"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
